"""Initial migration

Revision ID: 0fe5714c09a9
Revises: 
Create Date: 2024-02-28 21:19:58.906882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fe5714c09a9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('events', sa.Column('next_sheet_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'next_sheet_id')
    op.drop_column('events', 'active')
    # ### end Alembic commands ###
